# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.21"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: SigEnergy EVDC SoC Range Manager"
  org.opencontainers.image.description: "Keeps an EV's state of charge between a high and a low limit in V2X mode, by starting and stopping a Sigenergy DC charger"
  org.opencontainers.image.source: "https://github.com/thewhale21/HA_Addons"
  org.opencontainers.image.licenses: "MIT"
